const codes = `C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002349.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000422.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH603399.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000707.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH600860.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002006.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000838.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000683.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH601001.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002176.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000537.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002453.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH600172.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH600256.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000056.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH600367.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH601666.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH601699.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000815.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH601101.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH603800.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002667.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ000983.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH600481.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002529.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002613.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH603398.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SH600348.json
C:\\Users\\admin\\Documents\\stork_data\\storkData\\SZ002011.json`